### PR TITLE
Homepage card update 2019-03-20

### PR DESCRIPTION
**Pull request by stephaniehobson**
Updates to cards 1-3 outlined in[ this spreadsheet](https://docs.google.com/spreadsheets/d/1M49hOsXVGaIfogCDZKDYFOJJZu-gQkKaTuNrefuUk7M/edit#gid=895372766). Card 1 should be a video.

### CODE REVIEW

**Comment by stephaniehobson** [comment]
@agibson what are you using for image compression? I used all my best tricks and some of these are still twice the size of the previous ones (though maybe that's just because the old ones were simpler?)

**Comment by alexgibson** [comment]
> @agibson what are you using for image compression? I used all my best tricks and some of these are still twice the size of the previous ones (though maybe that's just because the old ones were simpler?)

I use [tinypng](https://tinypng.com/) mostly, but also [ImageOptim](https://imageoptim.com/mac)

**Review by alexgibson — APPROVED** [review]
Updates lgtm. I'll hold off merging incase you want to recompress the images, but you can also do that in another commit. Up to you 🖼

**Comment by stephaniehobson** [comment]
I'd already used tinypng and ImageOptim did not make any significant improvements to it. I guess these images are just not as compressible.

**Pull request merged**
