### PR TITLE
Add German homepage card data

### PR DESCRIPTION
**Pull request by alexgibson**
Adds initial set of editorial cards for the upcoming German home page redesign.

### CODE REVIEW

**Comment by pmac** [comment]
Is this content really all fully independent? No shared images or number of cards or anything? Having another page name is fine, but you don't have to if they're all in separate language files.

**Comment by alexgibson** [comment]
> Is this content really all fully independent? No shared images or number of cards or anything? Having another page name is fine, but you don't have to if they're all in separate language files.

This content is all custom and in no way related to the English card content. I don't think it's very likely that this admin will get much 1:1 translated content. Regional marketing is the big focus for this type of thing.

**Comment by alexgibson** [comment]
Also: two entirely separate teams are responsible for each home page locale. I'd expect updates to happen independently, so I think separating those concerns will likely be an easier ride.

**Comment by pmac** [comment]
great. thanks.

**Pull request merged**
