### PR TITLE
Port Gitlab CI job to GH Actions

### PR DESCRIPTION
**Pull request by stevejalim**
This changeset attempts to copy the Gitlab CI work to a GH Action.

The shell script may need further work:
* The action may lack the git permissions that the script expects, because these are not run on a runner machine with SSH keys installed
* The target bucket is still the AWS S3 bucket - we should probably move that to Google Cloud Storage, which will mean a reworking of the `push.sh` script

### CODE REVIEW

**Comment by stevejalim** [comment]
@pmac and @bkochendorfer I'd def welcome your thoughts on whether to point this at the GCS bucket now, or later -- I don't know how much we need to change the content cards any more

**Comment by pmac** [comment]
Perhaps @slightlyoffbeat would know if there are any plans to update those cards. My understanding is that the home page (including that for the locales covered by this repo) will be redesigned soon and that these cards will go away. So my guess is that we can just let this become superfluous naturally, but we can verify with Dan.

**Comment by pmac** [comment]
That said this looks good and we can go ahead and merge this so we can continue with GitLab removal.

**Review by pmac — APPROVED** [review]
🐘

**Review by bkochendorfer — COMMENTED** [review]
Do you need to add the credentials to push to that bucket and fetching them as well?

**Comment by stevejalim** [comment]
@bkochendorfer I was expecting to see AWS creds in the secrets on GL https://gitlab.com/mozmeao/www-admin/-/settings/ci_cd - but there are none there. Were they baked into the gitlab-runner image, I wonder? (or did the GL runner not need them if it was in a trusted network spot?)

**Comment by stevejalim** [comment]
@bkochendorfer 

> Do you need to add the credentials to push to that bucket and fetching them as well?

Good call yes. I imagine the GL runner had them build in. I've added support for them in https://github.com/mozmeao/www-admin/pull/103/commits/3c72c2752dfc82946b233b688cd332b3d11db9db but don't have them set as repo secrets yet -- do you know which ones I should use from the password vault?

**Comment by pmac** [comment]
> Were they baked into the gitlab-runner image, I wonder?

Yes and no. The gitlab runner is in AWS and that machine had IAM permission for the s3 buckets, so it Just Worked[tm].

**Comment by bkochendorfer** [comment]
Same as my comment on https://github.com/mozmeao/www-experiment-media/pull/1#issuecomment-1534904642 we probably need to update the code here to push to GCS instead of S3

**Pull request merged**
