### PR TITLE
Remove old en-US homepage cards

### PR DESCRIPTION
**Pull request by alexgibson**
The new cards are [in production](https://www.mozilla.org/en-US/), so the old set should now be safe to remove?

### CODE REVIEW

**Review by pmac — APPROVED** [review]
🥇 Thanks for doing the cleanup!!

**Comment by pmac** [comment]
My one question is whether there are still demos out there using the old card home page? And if so is that a big deal if they break?

**Comment by alexgibson** [comment]
> My one question is whether there are still demos out there using the old card home page? And if so is that a big deal if they break?

Should be fixed by a rebase and redeploy, right? If so, I think removing these will likely be ok?

**Comment by pmac** [comment]
> Should be fixed by a rebase and redeploy, right? If so, I think removing these will likely be ok?

Yes indeed. Sounds good to me 👍

**Pull request merged**
